name: Python CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Python
        run: |
          python3 --version
          pip3 --version

      - name: Create virtual environment
        run: python3 -m venv venv

      - name: Install dependencies
        run: |
          . venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python project
        run: |
          . venv/bin/activate
          python unified_main.py
