name: Python CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create virtual environment
        run: python3 -m venv $VENV

      - name: Install dependencies
        run: |
          . venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python project with PM2
        run: |
        
          pm2 delete aipython-github 
          pm2 start "uvicorn unified_main:app --host 0.0.0.0 --port 8001" --name aipythons
          pm2 save
